name: Compile Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install SDL2
      run: |
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        ./configure; make; sudo make install
        cd ..
      
    - name: Test for compilation errors
      run: make
      
    - name: Clean up
      run: make clean

